### ISSUE TITLE
Group same size width definitions together

### ISSUE THREAD

**Issue by bcinarli** [bcinarli/melange#5]
For better optimization, instead of having

``` css
.one-half { width: 50% }
.two-quarters { width: 50% }
.four-eighths { width: 50% }
```

group them together 

``` css
.one-half, .two-quarters, .four-eighths { width: 50% }
```
